### PR TITLE
Don't transform modules with import/export

### PR DESCRIPTION
**Pull request by Rich-Harris**
Even if they contain CJS features like `require`, `global` etc. Ref https://github.com/rollup/rollup-plugin-commonjs/issues/88#issuecomment-243555761

### CODE REVIEW

**Comment by talmobi** [comment]
Had this issue with the recently released newest version of redux@3.6.0 (https://github.com/reactjs/redux/releases) which updated its symbol-observable dependency to version 1.0.2 (https://github.com/blesh/symbol-observable/blob/master/CHANGELOG.md) with es6 support.

A temporary fix is to simply ignore symbol-observable specifically as an exclude field in the commonjs plugin.

I just want to say that I tested this PR and it worked out of the box with the newest version of redux@3.6.0 and its updated symbol-observable dependency (and as a result fixed my build and dev npm scripts)

People using redux with the hat character ^ in their dependencies (like I did) will at some points auto update to 3.6.0 and come across this issue that this PR seems to fix.

The only there difference is that using this PR rollup-plugin-version logs out a message when running rollup/build script (not an error)
```
The `this` keyword is equivalent to `undefined` at the top level of an ES module, and has been rewritten
```

Other than that everything seems to be working the same.

references: https://github.com/blesh/symbol-observable/issues/21

**Comment by TrySound** [comment]
You don't need this plugin anymore to build redux. Just set rollup option `context: 'window'`.

**Comment by talmobi** [comment]
Ahh, very good, thanks -- still need the plugin for other libraries though, and unless you exclude symbol-obvservable you get the build error without this PR.

**Comment by danbucholtz** [comment]
I have verified that this fixes #100

**Comment by blesh** [comment]
Thanks for your work on this @Rich-Harris

**Comment by Rich-Harris** [comment]
Sorry for the delay everyone! Just released this as 5.0.0 since it's potentially a breaking change, along with another PR (#106) which should bring bundle sizes down a bit.

**Pull request merged**
