### PR TITLE
Keep the order of execution for require calls

### PR DESCRIPTION
**Pull request by dralletje**
This turned out to be a problem when I tried importing RxJs, as it depends on one required file being executed before another. This PR will make sure the order is maintained, so it at least fixes some cases.

I’ve also added a test; I always wanted to say I added ‘tests’ but I really couldn’t think of another edge case to test ;)

Relevant issue on other repo https://github.com/cyclejs/cycle-core/issues/212

### CODE REVIEW

**Comment by dralletje** [comment]
@Victorystick Anything on this though? As this is necessary for browserify/webpack packages as well :/

**Comment by eventualbuddha** [comment]
So this will cause rollup to add imports in the source order of the requires.  That isn't guaranteed to be the actual order, but it is better than it was before so :+1:

**Comment by dralletje** [comment]
@eventualbuddha most packages won't do anything but importing in the top of the file, so for them it's enough. Maybe we should even issue a warning when something is being required in the not-top-level? Because that would hoist it to the top of the file, totally losing context :/

**Comment by ulrik59** [comment]
@dralletje Could you resolve conflicts so it can be merged ? I also need this evolution in order to use Bootstrap. Great work by the way !

**Comment by dralletje** [comment]
Sorry it took so long, but I rebased, hahaha :-)

**Comment by TrySound** [comment]
Thanks!

**Comment by TrySound** [comment]
Sorry :)

**Comment by dralletje** [comment]
Hahaha, thanks :D!

**Pull request merged**
