### PR TITLE
Deconflict reserved keywords. Fixes #116

### LINKED ISSUE #116: Reserved keywords as properties of module.exports are transpiled into named exports, which causes "unexpected token" errors.
Consider:

``` javascript
module.exports.delete = 'foo';
```

This will get transpiled into:

``` javascript
var delete = 'foo';

var mycjsmodule = {
    delete: delete
};

export default mycjsmodule;
export { mycjsmodule as __moduleExports };
export { delete };
```

Which will cause a SyntaxErrors on `var delete = 'foo';` and `export { delete };`

~~Since it's impossible to do `import { delete } from './mycjsmodule'` anyways, it would be safe to not create named exports for reserved-keyword properties of module.exports.~~ EDIT: Apparently it's possible to import a reserved keyword like that, as long as it's destructured, at least according to babel! Not sure if that's desired behavior.

### PR DESCRIPTION
**Pull request by lxe**
Fixes #116

### CODE REVIEW

**Comment by leeyeh** [comment]
Any news here?

**Comment by Rich-Harris** [comment]
Merged and released as 6.0.0, sorry for the delay

**Comment by decombs12** [comment]
I know this like 2 years later, but I've got an "unexpected token" problem regarding the '.' in front of '.then' frustrating my goals.

I'm a complete newb at this, but have the following showing the problem from cmd's cli:

ERROR in ./resources/assets/js/custom.js
Module build failed: SyntaxError: C:/xampp/htdocs/marxmanager/resources/assets/js/custom.js: Unexpected token (6:2)

  4 |
  5 |   axios.delete('/bookmarks/'+id);
> 6 |           .then(function() {
    |           ^
  7 |                   window.location.reload();
  8 |           });
  9 |           .catch(function(error) {

 @ ./resources/assets/js/app.js 9:0-19
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

From what I can tell, I have version 0.6.0 of axios.

**Comment by adrianheine** [comment]
What does your problem have to do with this pull request?

**Comment by decombs12** [comment]
Sorry, nothing. Like I said, a complete newb here. Pardon me.

Besides I fixed it anyway.

**Pull request merged**
