### PR TITLE
Make unwrapExports only pick out default when it exists

### PR DESCRIPTION
**Pull request by marijnh**
Now that I'm actually awake, I think it's rather obvious how issue #224 should be solved. Take a look!

### CODE REVIEW

**Comment by marijnh** [comment]
Heyyy there 👋, any chance this could get a look?

**Comment by lukastaegert** [comment]
Hi @marijnh, sorry you have been waiting for so long. I just took a look at your change and to me it seems that this should work well in all cases 👍.

However, as this issue is somewhat non-trivial, could you add a test that is fixed by your change? Something like what you posted as an example in #224 should be fine. This is important as it
serves as documentation for this change. If anyone wonders why this change was made and starts refactoring code, the red test will tell them right away.

If you don't feel up to it, I can do it for you, but this is your PR after all 😉

**Comment by marijnh** [comment]
Good point. I've updated the commit to include a test.

**Comment by lukastaegert** [comment]
Until @Rich-Harris is back at the internet to publish a new version, you can install a version containing this fix via
```bash
npm install github:rollup-plugin-commonjs@rollup/rollup-plugin-commonjs#bundled-v8.2.3
```
which should contain all necessary build artefacts.

**Comment by adrianheine** [comment]
`8.2.4` is released now and includes the fix.

**Pull request merged**
