### PR TITLE
Fix ignore global

### PR DESCRIPTION
**Pull request by dmitrage**

### CODE REVIEW

**Comment by TrySound** [comment]
@dmitrage Hi! Thanks for PR. Can you provide test case please?

**Comment by dmitrage** [comment]
@TrySound Hi! Instead I've added comment with "require" to the existing one that was actually skipped because of the firstpass check. 

Or should I create different cases for the firstpass regexp, Identifier and ThisExpression in this PR?

**Comment by TrySound** [comment]
@dmitrage Better different. Caz it's not actually ignore-global

**Comment by TrySound** [comment]
But you may combine them in one.

**Comment by dmitrage** [comment]
@TrySound I've updated test case to cover ignoreGlobal feature:
- try to skip module by firstpass, excluding "global" pattern from regexp
- do not mark "uses.global" when "global" identifier is found (implemented in this PR)
- do not mark "uses.global" when global "this" is found

Is that what you meant?

**Comment by Rich-Harris** [comment]
Thanks! Sorry for the slow turnaround, released as 4.0.1

**Pull request merged**
