### PR TITLE
Optimise module exports

### LINKED ISSUE #4: Optimize `module.exports = …` pattern
This is an extremely common pattern used in cjs modules. rollup-plugin-commonjs currently creates suboptimal code for that, see the example from https://github.com/zloirock/core-js/issues/125#issuecomment-152738215:

```js
var exports$198 = {};
var module$198 = { 'exports': exports$198 };
module$198.exports = require$$0$5.document && document.documentElement;

// OR

var exports$129 = {};
var module$129 = { 'exports': exports$129 };
module$129.exports = function(it){
  return typeof it === 'object' ? it !== null : typeof it === 'function';
};
```

If rollup-plugin-commonjs were a little bit smarter, it could avoid allocating the unused `exports` var/object in that case.
It it were even smarter, it may also be possible to avoid the `modules` map too, but I guess that would depend on the importer side, so it might not be feasible.

### PR DESCRIPTION
**Pull request by Victorystick**
With this PR we will try to optimise assignments to `module.exports` where we can determine that it's safe.

```js
// example.js
module.exports = function(it){
  return typeof it === 'object' ? it !== null : typeof it === 'function';
}
```

```js
// master branch
var example = (function (module) {
var exports = module.exports;
module.exports = function(it){
  return typeof it === 'object' ? it !== null : typeof it === 'function';
}
return module.exports;
})({exports:{}});

export default example;
```

```js
// optimise-module-exports branch
function example(it){
  return typeof it === 'object' ? it !== null : typeof it === 'function';
}

export default example;
```

@Swatinem Does this fix #4 for you?

### CODE REVIEW

**Comment by Swatinem** [comment]
You have to make sure the `module.exports = ` expression is at the file root.
https://github.com/zloirock/core-js/blob/master/modules/_redefine.js <- this file is getting transformed to invalid code:

```
(export default function(O, key, val, safe){
  if(typeof val == 'function'){
    val.hasOwnProperty(SRC) || hide(val, SRC, O[key] ? '' + O[key] : TPL.join(String(key)));
    val.hasOwnProperty('name') || hide(val, 'name', key);
  }
  if(O === global){
    O[key] = val;
  } else {
    if(!safe){
      delete O[key];
      hide(O, key, val);
    } else {
      if(O[key])O[key] = val;
      else hide(O, key, val);
    }
  }
})(Function.prototype, TO_STRING, function toString(){
  return typeof this == 'function' && this[SRC] || $toString.call(this);
});
```

**Comment by Swatinem** [comment]
Also if you do the export resolution *after* transforming the require calls, you could also optimize cases like this: https://github.com/zloirock/core-js/blob/master/modules/_html.js

```js
module.exports = require('./_global').document && document.documentElement;
```

Right now its not treated as staticValue because of the require() call. After the require transform, it should end up being a staticValue.

**Comment by Swatinem** [comment]
Same for https://github.com/zloirock/core-js/blob/master/modules/_path.js

That is a really ridiculous case for why this optimization is needed. No matter which module bundler you use, that 35 byte file surely ends up taking up more than double that in any bundler other than rollup :-)

**Comment by Victorystick** [comment]
Indeed. Ideally a single
```js
module.exports = require('...');
```
statement should transform to
```js
export * from '...';
export { default } from '...';
```

I'll look into all these things. :+1:

**Comment by Victorystick** [comment]
@Swatinem Mind taking another look?

**Comment by Swatinem** [comment]
One step further, but now I have two related issues.

The build now breaks because `Error: Module …/core-js/modules/es5.js does not export default (imported by /tmp/1151026-32286-1ve7p9z.js)`

Like I said, its 2 problems at once:

* The file really does not write to module.exports, so no intro/outro is generated and thus no export defaults there. (Maybe you could just give a `export default {}` in that case.
* The auto generated file (which is basically the same as https://github.com/zloirock/core-js/blob/master/shim.js) has a lot of plain require calls, so imports for side effects. rollup-plugin-commonjs actually turns those into `import foo from "…"; foo;` which then breaks.

**Comment by Victorystick** [comment]
@Swatinem I pushed a commit to handle bare `require`s just seconds before your comment. :stuck_out_tongue_closed_eyes:

**Comment by Swatinem** [comment]
Yes, I’ve seen it. :-)

So compiling core-js works now. The generated bundle is ~20k smaller, but the minified version is ~1k larger for whatever reason.

**Comment by Victorystick** [comment]
I think it's because of how `webpack` wraps each CommonJS module. This is the only overhead that separates each module:
```js
}, function (module, exports, __webpack_require__) {

// minified
},function(a,b,c){
```

Rollup has more overhead. This is it's current wrapper:
```js
var main = (function (module) {
  var exports = module.exports;
  ...
  return module.exports;
})({exports:{}});

export default main;
```
Let's look at an example to see how this ends up:
```js
// main.js
module.exports = require('./something.js').Foo;

// with Webpack
function (module, exports, __webpack_require__) {
  module.exports = __webpack_require__(5).Foo;
}

// with Rollup
var main = (function (module) {
  var exports = module.exports;
  module.exports = require$$0.Foo; // the import available through an identifier
  return module.exports;
}({ exports: {} );

// minified Webpack, ~35 bytes
function(a,b,c){a.exports=c(5).Foo}

// minified Rollup, ~75 bytes
var a=function(o){o.exports;return o.exports=r.Foo,o.exports}({exports:{}})
```

**Comment by Swatinem** [comment]
Yes I remember rollup used to have a thinner wrapper a few versions ago.

Not sure if @zloirock would actually want to reconsider switching to rollup if it could generate smaller minified bundles :-)

**Comment by Victorystick** [comment]
> Yes I remember rollup used to have a thinner wrapper a few versions ago.

That's right. @Rich-Harris From [this Git commit message](https://github.com/rollup/rollup-plugin-commonjs/commit/8595beb0da831b6269968e37613523be22c15411) it appears that the modules are wrapped in closures to allow more readable outputs; is that the only reason? The wrappers as they are now add quire a bit of overhead.

If they are necessary for some other reason, they can be further optimised. I could whip something up, but if the wrappers aren't even necessary, I'd prefer to just have them removed.

**Comment by zloirock** [comment]
@Swatinem you can add PR when it will be done. Could be good optimise `core-js` load time for the next big release.

**Comment by Victorystick** [comment]
Rebased.

**Comment by pygy** [comment]
I've been trying to build this branch, but the `npm run build` script relies on a default config file that I'm not able to find (and neither is Rollup AFAICT). The build artifact is thus non-existant.

I'm tying to determine if this patch improves the situation here: https://github.com/pygy/trollup

Here's the resulting `bundle.js`:

```JS
'use strict';

var baz = 4;

var qux = (function (module) {
var exports = module.exports;
module.exports.qux = 5
module.exports.extra = 6
return module.exports;
})({exports:{}});

var qux = qux.qux;

exports.baz = baz;
exports.qux = qux;
```

**Comment by pygy** [comment]
There are three issues BTW, one is the lack of pruning of the `extra` field, the other is all the useless `var exports` definition, and the last is the presence of two `var qux` declarations, which, while not strictly buggy is a bit confusing.

**Comment by pygy** [comment]
At last, I got it to build. First time I try to install npm modules from git. cloning the plugin in the `node_modules` directory did the trick.

So, now, I get this:

```JavaScript
'use strict';

var baz = 4;

var exports$1 = {};
var module$1 = { exports: exports$1 };
module$1.exports.qux = 5
module$1.exports.extra = 6
var qux$1 = exports$1.qux;

exports.baz = baz;
exports.qux = qux$1;

```

Which is definitely better :-)

No tree shaking yet for the `extra` field, though.

**Comment by Rich-Harris** [comment]
Finally got a chance to dig into this properly. Afraid everything got screwed up a bit with the various overlapping branches and this isn't mergeable – sorry – so I've been experimenting with reinstating some of these additions without the confusion caused by the back-and-forth over module wrappers.

To be honest, I think we might be going a bit overboard here. The purpose of this plugin isn't really to optimise CommonJS modules, it's just to allow people to use external CommonJS dependencies until everyone starts distributing ES6 modules. Adding so much complexity to massage down the filesizes of transpiled legacy modules makes me nervous – it will make future fixes and additions (say, if we decide we really need to support lazy inline `require` calls, or support some Browserify idiom like polyfilling `Buffer`) harder. It's likely to consume energy that would be better spent on improving Rollup itself and helping people adopt ES6 modules than on reducing the incentive to switch.

What does everyone reckon?

**Comment by Victorystick** [comment]
I agree. I admit that I got a bit overboard with this. I got enticed by the possibility of Rollup beating CommonJS bundlers at their own game. :stuck_out_tongue_winking_eye:

I'll experiment with optimising CommonJS elsewhere.

**Comment by Swatinem** [comment]
I’m sad to see this go. But you are absolutely right to rather promote es2015 modules than to optimize legacy module systems.

**Pull request closed without merging**
