### PR TITLE
Add support for transpiled modules

### LINKED ISSUE #10: Support CommonJS modules transpiled by Babel
The CommonJS plugin doesn't handle ES6 transpile-style exports very well. I present two examples why support must be improved:

### Because this isn't very nice
```js
// source
export default function () { return 1337; }
```

```js
// after babel
"use strict";

exports.__esModule = true;

exports["default"] = function () {
  return 1337;
};

module.exports = exports["default"];
```

```js
// after rollup-plugin-commonjs
var leet = (function (module) {
  var exports = module.exports;
  "use strict";

  exports.__esModule = true;

  exports["default"] = function () {
    return 1337;
  };

  module.exports = exports["default"];
  return module.exports;
})({exports:{}});

var __esModule = leet.__esModule;

export { __esModule };export default leet;
```
That's quite a bit of bloat.

### Worse: code like this breaks
```js
// `babel-runtime/core-js/get-iterator.js` source
module.exports = { "default": require("core-js/library/fn/get-iterator"), __esModule: true };
```
We do not give `exports['default']` special treatment.
```js
// after rollup-plugin-commonjs
import require$$0 from 'core-js/library/fn/get-iterator';

var getIterator = (function (module) {
var exports = module.exports;
module.exports = { "default": require$$0, __esModule: true };
return module.exports; // an object is exported, not a function
})({exports:{}});

export default getIterator;
```

### PR DESCRIPTION
**Pull request by Victorystick**
_Don't merge yet_

This PR tracks how best to handle CommonJS modules that have already been transpiled by Babel, TypeScript or something similar. These CommonJS modules define a `__esModule` property on their exports object, and export their default export as a `default` property.

We should:
1. remove the `__esModule` property
2. use the `default` property for the default export instead of the `module.exports` object

Fixes #10

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Would it be appropriate to warn users in this situation? It may be that we're dealing with external packages, in which case the user may have limited control, but it might help people understand that their Babel config is messed up etc

**Comment by flying-sheep** [comment]
messed up? does this mean it’s somehow not working as intended? why?

**Comment by Rich-Harris** [comment]
@flying-sheep Messed up as in Babel is being used to convert ES6 modules to CommonJS modules, which means Rollup has to convert them *back* to ES6 modules so that it can bundle them (quite possibly in order to generate a CommonJS bundle). Keeping everything as ES6 until you need to run it is the name of the game.

**Comment by flying-sheep** [comment]
ok, but how? `jsnext:main` should point to a “distributable” package, not a ES2015 package… should we really introduce another field and copy of the lib for an ES2015 version?

i’ll comment in rollup/rollup#337 about it.

for this issue and plugin, i think we should simply detect the most common ways stuff is distributed and be practical instead of idealistic. this is a practical plugin, written for a world of commonjs modules. it should “get” as many of them as possible.

**Comment by Rich-Harris** [comment]
Should have been more specific – I meant keeping everything as ES6 *modules* is the goal, since that's the only thing that's getting translated back and forth otherwise.

**Comment by flying-sheep** [comment]
makes sense. this is a frequent language confusion in the discussions here.

but still: both should be supported as we can’t hope to convince everyone and therefore be practical.

1. let’s help redux with fixing their use of `jsnext:main`
2. let’s finish and pull this PR

then we can actually work productively with rollup as node_modules bundler

**Comment by Victorystick** [comment]
Looks good to me. :+1:

**Comment by Rich-Harris** [comment]
Have released this as 2.0.0 (since it's technically a breaking change) – it doesn't include warnings about already-transpiled modules, but we could revisit that in future if we choose

**Comment by bfred-it** [comment]
Sorry, I think this change is indeed breaking support of rollup modules in browserify/babel. If you export `default` but not `__esModule`, browserify/babel won't pick that up. I had left a comment here too: https://github.com/rollup/rollup/issues/496#issuecomment-198746673

**Pull request merged**
