### PR TITLE
Fix duplicate export error (e.g. when importing Cheerio)

### PR DESCRIPTION
**Pull request by caleb531**
Fixes https://github.com/rollup/rollup/issues/1637

I've tried to follow @kzc's [patch and test cases](https://github.com/rollup/rollup/issues/1637#issuecomment-330338099) as closely as I could, but please let me know if I need to make any changes.

Thanks,
Caleb

### CODE REVIEW

**Comment by lukastaegert** [comment]
Looks great, sorry to have kept you waiting 🎉

**Comment by caleb531** [comment]
@lukastaegert Great, thank you! When could I expect the next release of rollup-plugin-commonjs?

**Comment by lukastaegert** [comment]
Give me a few more minutes 😀

**Comment by lukastaegert** [comment]
Oh no, maybe I overestimated my powers here which only seem to extend to merging PRs put not to publishing new versions. I will PM @Rich-Harris as he will probably need to do this.

**Comment by lukastaegert** [comment]
Until @Rich-Harris is back at the internet to publish a new version, you can install a version containing this fix via
```bash
npm install github:rollup-plugin-commonjs@rollup/rollup-plugin-commonjs#bundled-v8.2.3
```
which should contain all necessary build artefacts.

**Pull request merged**
