### PR TITLE
Fix #232 - require collision.

### LINKED ISSUE #232: Conflict detection/avoidance for "require" aliases
React 16 bundles now use rollup as well; this means some of them may contain aliased requires, which will clash with the ones generated by the local rollup.
Example:
[React 16.0.0.0, node_modules/react/cjs/react.development.js](https://npm.runkit.com/react/cjs/react.development.js?t=1506456013752)
```
var objectAssign$1 = require('object-assign');
var require$$0 = require('fbjs/lib/warning');
```

gets converted to

```
var objectAssign$1 = require$$0;
var require$$0 = warning_1;
```

, which is obviously invalid.

This situation could be avoided if the name candidates were tested for uniqueness while increasing the uid.
Alternatively, either the separator ($$) or the start uid (0) could be configurable in transform.js .

### PR DESCRIPTION
**Pull request by mbostock**
Fixes #232 rollup/rollup#1655.

### CODE REVIEW

**Comment by mbostock** [comment]
Gentle ping?

**Comment by lukastaegert** [comment]
Hi @mbostock, thanks for the fix, looks great! 🎉
But since this issue is non-trivial and it is quite possible we break this functionality again by some future update we should certainly add a test for this. Would you add one to your PR?
If you don't have the time (I understand this issue is somewhat important to quite a few people) or don't feel up to it I can do this for you but of course this is your PR after all 😉

Once we have a test, I will merge this right away!

**Comment by mbostock** [comment]
I posted a trivial test case 11 days ago here https://github.com/rollup/rollup/issues/1655#issuecomment-332337049 but yes, I can spend some time now looking at how your tests are setup.

**Comment by mbostock** [comment]
Test added in 386a1e7.

**Comment by lukastaegert** [comment]
Great, thanks 🎉

**Comment by lukastaegert** [comment]
Until @Rich-Harris is back at the internet to publish a new version, you can install a version containing this fix via
```bash
npm install github:rollup-plugin-commonjs@rollup/rollup-plugin-commonjs#bundled-v8.2.3
```
which should contain all necessary build artefacts.

**Pull request merged**
