### PR TITLE
Optimisation

### PR DESCRIPTION
**Pull request by Rich-Harris**
This PR allows the majority of CommonJS modules to be transformed without wrapping. In other words, this...

```js
// foo.js
module.exports = 42;
```

...becomes this...

```js
var foo = 42;

export default foo;
export { foo as __moduleDefault };
```

...rather than this:

```js
var foo = createCommonjsModule(function(module) {
  module.exports = 42;
});

export default foo;
export { foo as __moduleDefault };
```

In many cases this makes modules tree-shakeable. It doesn't *yet* optimise situations like this:

```js
module.exports = {
  foo: foo,
  bar: bar
};
```

Will release as 5.0.0 (major version bump) as it depends on Rollup 0.35.

### CODE REVIEW

**Comment by montogeek** [comment]
Will this work with Lodash?

**Comment by Rich-Harris** [comment]
I'd recommend using `lodash-es` rather than `lodash`. This won't have any effect on the tree-shakeability of the library itself – all it means is that in a situation like this...

```js
exports.a = 1;
exports.b = 2;
```

...where `a` is used in the bundle but `b` is not, the `b` can be removed. Previously there was no way to remove any code from a transformed CommonJS module.

**Comment by montogeek** [comment]
Thanks!

**Comment by montogeek** [comment]
Thanks @jdalton It should be compatible with https://github.com/rollup/rollup-plugin-babel, right?

**Pull request merged**
